# fly.toml app configuration file generated for gizztapes2 on 2024-12-27T17:29:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gizztapes2'
primary_region = 'bos'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source="sqlite3"
  destination="/mnt/sqlite3"