name: Deploy Staging
on:
  push:
    branches: [master]
jobs:
  staging:
    runs-on: ubuntu-latest
    concurrency: deploy-staging
    steps:
      - uses: actions/checkout@v6
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -a gizztapes2-staging -c fly.staging.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_STAGING_TOKEN }}
